version: "2"

services:

  web:
    # build: .
    image: ctftraining/lctf_2018_bestphp_s_revenge
    restart: always
    ports:
      - "127.0.0.1:8081:80"
    environment:
      - FLAG=flag{test_flag}
